default:
    trainer: ppo
    batch_size: 2048
    buffer_size: 20480
    lambd: 0.92
    num_epoch: 2
    time_horizon: 5000
    beta: 1e-4
    epsilon: 0.15
    hidden_units: 500
    learning_rate: 3e-4
    learning_rate_schedule: constant
    max_steps: 1.0e8
    normalize: true
    num_layers: 3
    sequence_length: 64
    summary_freq: 10000
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.999
    use_recurrent: false
    memory_size: 64
    self_play:
        window: 10
        play_against_current_self_ratio: 0.5
        save_steps: 50000
        swap_steps: 50000
# Soccer:
#     normalize: false
#     max_steps: 5.0e7
#     learning_rate_schedule: constant
#     batch_size: 2048
#     buffer_size: 20480
#     hidden_units: 512
#     time_horizon: 1000
#     num_layers: 2
#     self_play:
#         window: 10
#         play_against_current_self_ratio: 0.5
#         save_steps: 50000
#         swap_steps: 50000