default:
    trainer: ppo
    batch_size: 2000
    buffer_size: 300000
    lambd: 0.92
    num_epoch: 2
    time_horizon: 256
    beta: 1e-5
    epsilon: 0.2
    hidden_units: 256
    learning_rate: 1e-5
    learning_rate_schedule: linear
    max_steps: 1.0e8
    normalize: false
    num_layers: 2
    sequence_length: 64
    summary_freq: 10000
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.999
    use_recurrent: false
    memory_size: 64
