default:
    trainer: ppo
    batch_size: 2000
    buffer_size: 50000
    lambd: 0.97
    num_epoch: 5
    time_horizon: 1000
    beta: 1e-2
    epsilon: 0.15
    hidden_units: 256
    learning_rate: 1e-5
    learning_rate_schedule: linear
    max_steps: 1.0e8
    normalize: false
    num_layers: 2
    sequence_length: 64
    summary_freq: 10000
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
    use_recurrent: false
    memory_size: 64
