default:
    trainer: ppo
    batch_size: 4500
    buffer_size: 45000
    lambd: 0.92
    num_epoch: 3
    time_horizon: 500
    beta: 1.0e-4
    epsilon: 0.2
    hidden_units: 400
    learning_rate: 1.0e-4
    learning_rate_schedule: constant
    max_steps: 1.0e9
    normalize: false
    num_layers: 3
    sequence_length: 64
    summary_freq: 10000
    reward_signals:
        extrinsic:
            strength: 1
            gamma: 0.999
        # curiosity:
        #     strength: 0.005
        #     gamma: 0.99
        #     encoding_size: 256
    use_recurrent: false
    memory_size: 64
    self_play:
        window: 10
        play_against_current_self_ratio: 0.5
        save_steps: 50000
        swap_steps: 50000
        team_change: 100000