default:
    trainer: ppo
    batch_size: 9000
    buffer_size: 90000
    lambd: 0.92
    num_epoch: 4
    time_horizon: 1000
    beta: 1.0e-4
    epsilon: 0.25
    hidden_units: 500
    learning_rate: 1.5e-4
    learning_rate_schedule: constant
    max_steps: 1.0e9
    normalize: true
    num_layers: 2
    sequence_length: 64
    summary_freq: 90000
    reward_signals:
        extrinsic:
            strength: 1
            gamma: 0.999
        curiosity:
            strength: 0.002
            gamma: 0.99
            encoding_size: 256
    use_recurrent: false
    memory_size: 64
    self_play:
        window: 10
        play_against_current_self_ratio: 0.5
        save_steps: 100000
        swap_steps: 100000
        team_change: 200000