default:
    trainer: sac
    batch_size: 512
    buffer_size: 500000
    buffer_init_steps: 50000
    init_entcoef: 0.6
    train_interval: 5
    num_update: 1
    tau: 0.005
    time_horizon: 1400
    hidden_units: 256
    learning_rate: 1e-5
    learning_rate_schedule: constant
    max_steps: 2.0e6
    normalize: false
    num_layers: 2
    sequence_length: 64
    summary_freq: 10000
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
    use_recurrent: false
    memory_size: 64